"use client";

import { Suspense, useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { api, type ImageSlotDraft } from "../../../lib/api";
import { StageRail } from "../../../components/stage-rail";
import { ActionBar } from "../../../components/action-bar";
import { useToast } from "../../../components/toast";

interface ImagesPayload { slots: ImageSlotDraft[]; }

const RefreshIcon = () => (
  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" width="13" height="13">
    <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"/><path d="M21 3v5h-5"/><path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"/><path d="M8 16H3v5"/>
  </svg>
);

export default function ImageApprovalPage() {
  return (
    <Suspense fallback={<div className="page-inner"><div className="skeleton" style={{ height: 56, borderRadius: 12, marginBottom: 28 }} /><div className="skeleton" style={{ height: 300 }} /></div>}>
      <ImageApproval />
    </Suspense>
  );
}

function ImageApproval() {
  const params = useSearchParams();
  const router = useRouter();
  const { toast } = useToast();
  const approvalId = params.get("approvalId");
  const workflowRunId = params.get("runId") ?? "";

  const [slots, setSlots] = useState<ImageSlotDraft[]>([]);
  const [altOverrides, setAltOverrides] = useState<Record<number, string>>({});
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [regenerating, setRegenerating] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!approvalId) { setError("Missing approvalId"); setLoading(false); return; }
    api.getApproval(approvalId)
      .then((a) => {
        const payload = a.payload as ImagesPayload;
        setSlots(payload.slots);
        const seed: Record<number, string> = {};
        for (const s of payload.slots) {
          if (s.altTextSuggestion) seed[s.slotPosition] = s.altTextSuggestion;
        }
        setAltOverrides(seed);
      })
      .catch((e) => setError((e as Error).message))
      .finally(() => setLoading(false));
  }, [approvalId]);

  const allGenerated = useMemo(() => slots.length > 0 && slots.every((s) => !!s.generatedImageUrl), [slots]);

  async function handleRegenerate(slotPosition: number) {
    if (!workflowRunId) return;
    setRegenerating(slotPosition);
    try {
      const { slot } = await api.regenerateImage(workflowRunId, slotPosition);
      setSlots((prev) => prev.map((s) => (s.slotPosition === slotPosition ? slot : s)));
      if (slot.altTextSuggestion) {
        setAltOverrides((prev) => ({ ...prev, [slotPosition]: slot.altTextSuggestion ?? prev[slotPosition] ?? "" }));
      }
      toast(`Slot ${slotPosition + 1} regenerated`);
    } catch (e) {
      const msg = (e as Error).message;
      toast(msg, "err");
    } finally {
      setRegenerating(null);
    }
  }

  async function handleSubmit() {
    if (!workflowRunId || !allGenerated) return;
    setSubmitting(true);
    setError(null);
    try {
      const decision = {
        slots: slots.map((s) => {
          const edited = altOverrides[s.slotPosition]?.trim();
          const suggested = s.altTextSuggestion?.trim() ?? "";
          return edited && edited !== suggested
            ? { slotPosition: s.slotPosition, altTextOverride: edited }
            : { slotPosition: s.slotPosition };
        }),
      };
      await api.decideImages(workflowRunId, decision);
      const { approvalId: affId } = await api.startAffiliates(workflowRunId);
      router.push(`/approvals/affiliates?approvalId=${affId}&runId=${workflowRunId}`);
    } catch (e) {
      const msg = (e as Error).message;
      setError(msg);
      toast(msg, "err");
      setSubmitting(false);
    }
  }

  if (loading) return (
    <div className="page-inner">
      <div className="skeleton" style={{ height: 56, borderRadius: 12, marginBottom: 28 }} />
      <div className="skeleton" style={{ width: 200, height: 48, marginBottom: 24 }} />
      {[0, 1].map((i) => <div key={i} className="img-slot" style={{ marginBottom: 12 }}><div className="img-slot-thumb"><div className="skeleton" style={{ height: "100%", borderRadius: 8 }} /></div><div style={{ flex: 1 }}><div className="skeleton" style={{ height: 12, marginBottom: 8 }} /><div className="skeleton" style={{ height: 60 }} /></div></div>)}
    </div>
  );

  const generatedCount = slots.filter((s) => !!s.generatedImageUrl).length;

  return (
    <div className="page-inner">
      <StageRail current="/approvals/images" runId={workflowRunId} />

      <div className="page-header">
        <div className="page-eyebrow">Stage 3 of 6</div>
        <h1 className="page-title">Review <em>images</em></h1>
        <div className="page-sub">Generated by Ideogram from the blog draft prompts. Regenerate any slot, then edit alt text and confirm.</div>
      </div>

      {error && <div style={{ padding: "12px 16px", background: "var(--red-soft)", color: "var(--red)", borderRadius: 10, marginBottom: 20, fontSize: 13 }}>{error}</div>}

      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 20 }}>
        <div className="section-label">Image slots</div>
        <span className={`chip ${allGenerated ? "good" : "plain"}`}>
          {generatedCount}/{slots.length} generated
        </span>
      </div>

      <div style={{ marginBottom: 80 }}>
        {slots.map((slot) => {
          const hasImg = !!slot.generatedImageUrl;
          const isRegen = regenerating === slot.slotPosition;
          return (
            <div key={slot.slotPosition} className={`img-slot ${hasImg ? "approved" : ""}`}>
              <div className="img-slot-thumb" style={hasImg ? undefined : undefined}>
                {hasImg ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img src={slot.generatedImageUrl} alt={altOverrides[slot.slotPosition] ?? `slot ${slot.slotPosition}`} style={{ width: "100%", height: "100%", objectFit: "cover", borderRadius: 8 }} />
                ) : (
                  <div className="img-slot-thumb empty">
                    <div style={{ fontFamily: "var(--font-serif)", fontSize: 28, fontStyle: "italic", color: "var(--ink-faint)", marginBottom: 6 }}>?</div>
                    <div>Not generated</div>
                  </div>
                )}
                <div className="img-slot-num">#{slot.slotPosition + 1}</div>
              </div>

              <div className="img-slot-main">
                <div className="prompt">{slot.promptHint}</div>

                {hasImg && (
                  <>
                    <div className="field-label" style={{ marginTop: 10 }}>
                      <span>Alt text</span>
                      <span className="field-hint">{(altOverrides[slot.slotPosition] ?? "").length} chars</span>
                    </div>
                    <textarea
                      className="field"
                      rows={2}
                      value={altOverrides[slot.slotPosition] ?? ""}
                      onChange={(e) => setAltOverrides((prev) => ({ ...prev, [slot.slotPosition]: e.target.value }))}
                    />
                  </>
                )}

                <div className="img-slot-actions">
                  <button
                    type="button"
                    className="btn btn-ghost"
                    onClick={() => handleRegenerate(slot.slotPosition)}
                    disabled={isRegen || submitting}
                  >
                    {isRegen ? "Generating…" : <><RefreshIcon /> {hasImg ? "Regenerate" : "Generate"}</>}
                  </button>
                  {hasImg && <span className="chip good">✓ generated</span>}
                </div>
              </div>
            </div>
          );
        })}
      </div>

      <ActionBar
        onApprove={handleSubmit}
        approveLabel="Confirm images → affiliates"
        onBack="/approvals"
        disabled={!allGenerated || regenerating !== null}
        loading={submitting}
      />
    </div>
  );
}
